In [ ]:
import os
from torchvision.transforms import v2
from torchvision.io import decode_image
from torchvision.utils import save_image
import torch
import random

covid_dir = "./xrays/COVID"
healthy_dir = "./xrays/HEALTHY"


In [6]:
# Count how many COVID and how many HEALTHY xray images we have 

count_covid = len(os.listdir(covid_dir))
count_healthy = sum(1 for file in os.listdir(healthy_dir) if not file.startswith("augmented"))

print(f"covid: {count_covid}", f"healthy: {count_healthy}", sep="\n")

covid: 3875
healthy: 1348


In [7]:
# Images to apply augmentation
resamples = count_covid - count_healthy
print(resamples)

2527


In [ ]:
# Get a list of the healthy images as tensors
healthy_samples = [decode_image(healthy_dir+f"/{img}") for img in os.listdir(healthy_dir)]

# Get a random sample with replacement of size "resamples"
healthy_samples = random.choices(healthy_samples, k=resamples)
healthy_samples

[tensor([[[0, 0, 0,  ..., 0, 0, 1],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 2, 2],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]]], dtype=torch.uint8),
 tensor([[[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]]], dtype=torch.uint8),
 tensor([[[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          ...,
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]]], dtype=torch.uint8),
 tensor([[[ 77,  79,  76,  ..., 128, 132, 131],
          [ 79,  80,  77,  ..., 126, 130, 132],
          [ 79,  80,  78,  ..., 125, 126, 127],
          ...,
          [  0,   0,   0,  ...,   0,   0,   0],
          [  0,   0,   0,  ...,   

In [ ]:
len(healthy_samples)

2527

In [ ]:
# Apply vertical and/or horizontal flips with 80% chance each, on each image tensor 
transforms = v2.Compose([v2.RandomVerticalFlip(0.8), v2.RandomHorizontalFlip(0.8)])

# Store augmented images
for i, img in enumerate(healthy_samples):
    save_image(transforms(img).to(torch.float)/255, healthy_dir+f"/augmented_{i+1}.jpeg")

'\nimg = decode_image("./xrays/HEALTHY/1.jpeg")\nt_img = transforms(img).to(torch.float32)\nsave_image(t_img/255, healthy_dir+f"/1_1.jpeg")\n\nprint(img.shape)\nprint(t_img)\nprint(img)\n\nplt.figure()\nplt.imshow(t_img.permute(1,2,0), cmap= "gray", vmin=0, vmax=255)\nplt.figure()\nplt.imshow(img.permute(1,2,0), cmap= "gray", vmin=0, vmax=255)\n'